// Curated topic/subtopic presets for the Generator's quick-pick selects.
// Purely a convenience layer — the actual Topic/Subtopic fields stay free
// text, so a preset selection just fills them in and remains editable.
export const TOPIC_PRESETS = {
  'Climate Change': [
    'Global Warming Causes',
    'Rising Sea Levels',
    'Carbon Emissions',
    'Renewable Energy Transition',
    'Climate Policy',
    'Extreme Weather Events',
    'Deforestation Effects',
    'Climate Migration',
    'Ocean Acidification',
    'Sustainable Agriculture',
  ],
  'Artificial Intelligence': [
    'Machine Learning Basics',
    'AI in Healthcare',
    'Ethical Concerns of AI',
    'Automation and Jobs',
    'Natural Language Processing',
    'AI in Education',
    'Self-Driving Cars',
    'AI Bias and Fairness',
    'Robotics',
    'The Future of AI',
  ],
  'Public Health': [
    'Vaccination Programs',
    'Antibiotic Resistance',
    'Pandemic Preparedness',
    'Nutrition and Diet',
    'Mental Health Awareness',
    'Healthcare Access',
    'Chronic Disease Prevention',
    'Aging Population',
    'Health Misinformation',
    'Global Health Inequality',
  ],
  Globalization: [
    'International Trade',
    'Cultural Exchange',
    'Multinational Corporations',
    'Global Supply Chains',
    'Economic Inequality',
    'Immigration Patterns',
    'Global Labor Markets',
    'Trade Agreements',
    'Cultural Homogenization',
    'Global Financial Systems',
  ],
  Urbanization: [
    'Smart Cities',
    'Urban Green Spaces',
    'Housing Affordability',
    'Public Transportation',
    'Urban Sprawl',
    'City Planning',
    'Gentrification',
    'Traffic Congestion',
    'Urban Pollution',
    'Sustainable Urban Development',
  ],
  'Renewable Energy': [
    'Solar Power',
    'Wind Energy',
    'Hydroelectric Power',
    'Energy Storage',
    'Fossil Fuel Alternatives',
    'Energy Policy',
    'Grid Modernization',
    'Nuclear Energy Debate',
    'Energy Efficiency',
    'Green Hydrogen',
  ],
  'Social Media': [
    'Social Media Addiction',
    'Misinformation Spread',
    'Privacy Concerns',
    'Influencer Culture',
    'Mental Health Effects',
    'Social Media and Democracy',
    'Cyberbullying',
    'Digital Detox',
    'Algorithm Bias',
    'Youth and Social Media',
  ],
  'Higher Education': [
    'Online Learning',
    'Student Debt',
    'University Access',
    'Standardized Testing',
    'Academic Integrity',
    'STEM Education',
    'Study Abroad Programs',
    'Vocational Training',
    'Lifelong Learning',
    'University Rankings',
  ],
  'Mental Health': [
    'Stress Management',
    'Anxiety Disorders',
    'Workplace Mental Health',
    'Therapy Access',
    'Social Isolation',
    'Mental Health Stigma',
    'Mindfulness Practices',
    'Sleep and Mental Health',
    'Youth Mental Health',
    'Mental Health in Schools',
  ],
  Biotechnology: [
    'Genetic Engineering',
    'CRISPR Technology',
    'Cloning Ethics',
    'Biotech in Agriculture',
    'Personalized Medicine',
    'Stem Cell Research',
    'Synthetic Biology',
    'Biotech Regulation',
    'Gene Therapy',
    'Biotech and Food Security',
  ],
}
